
import sys
import argparse

ws2_array = [
    "NULL",
    "accept",
    "bind",
    "closesocket",
    "connect",
    "getpeername",
    "getsockname",
    "getsockopt",
    "htonl",
    "htons",
    "inet_addr",
    "inet_ntoa",
    "ioctlsocket",
    "listen",
    "ntohl",
    "ntohs",
    "recv",
    "recvfrom",
    "select",
    "send",
    "sendto",
    "setsockopt",
    "shutdown",
    "socket",
    "WSAStartup",
    "WSACleanup",
    "WSASetLastError",
    "WSAGetLastError",
    "WSAIsBlocking",
    "WSAUnhookBlockingHook",
    "WSASetBlockingHook",
    "WSACancelBlockingCall",
    "WSAAsyncGetServByName",
    "WSAAsyncGetServByPort",
    "WSAAsyncGetProtoByName",
    "WSAAsyncGetProtoByNumber",
    "WSAAsyncGetHostByName",
    "WSAAsyncGetHostByAddr",
    "WSACancelAsyncRequest",
    "WSAAsyncSelect",
    "FreeAddrInfoEx",
    "FreeAddrInfoExW",
    "FreeAddrInfoW",
    "GetAddrInfoExA",
    "GetAddrInfoExW",
    "GetAddrInfoW",
    "GetNameInfoW",
    "InetNtopW",
    "InetPtonW",
    "SetAddrInfoExA",
    "SetAddrInfoExW",
    "WEP",
    "WPUCompleteOverlappedRequest",
    "WSAAccept",
    "WSAAddressToStringA",
    "WSAAddressToStringW",
    "WSAAdvertiseProvider",
    "WSAAsyncGetHostByAddr",
    "WSAAsyncGetProtoByName",
    "WSAAsyncGetServByName",
    "WSACreateEvent",
    "WSADuplicateSocketA",
    "WSADuplicateSocketW",
    "WSAEnumNameSpaceProvidersA",
    "WSAEnumNameSpaceProvidersExA",
    "WSAEnumNameSpaceProvidersExW",
    "WSAEnumNameSpaceProvidersW",
    "WSAEnumNetworkEvents",
    "WSAEnumProtocolsA",
    "WSAEnumProtocolsW",
    "WSAEventSelect",
    "WSAGetLastError",
    "WSAGetOverlappedResult",
    "WSAGetQOSByName",
    "WSAGetServiceClassInfoA",
    "WSAGetServiceClassInfoW",
    "WSAGetServiceClassNameByClassIdA",
    "WSAGetServiceClassNameByClassIdW",
    "WSAHtonl",
    "WSAHtons",
    "WSAInstallServiceClassA",
    "WSAInstallServiceClassW",
    "WSAIoctl",
    "WSAIsBlocking",
    "WSAJoinLeaf",
    "WSALookupServiceBeginA",
    "WSALookupServiceBeginW",
    "WSALookupServiceEnd",
    "WSALookupServiceNextA",
    "WSALookupServiceNextW",
    "WSANSPIoctl",
    "WSANtohs",
    "WSANtohl",
    "WSAPoll",
    "WSAProviderCompleteAsyncCall",
    "WSAProviderConfigChange",
    "WSARecv",
    "WSARecvDisconnect",
    "WSARecvFrom",
    "WSARemoveServiceClass",
    "WSAResetEvent",
    "WSASend",
    "WSASendDisconnect",
    "WSASendMsg",
    "WSASendTo",
    "WSASetEvent",
    "WSASetServiceA",
    "WSASetServiceW",
    "WSASocketA",
    "WSASocketW",
    "WSAStringToAddressA",
    "WSAStringToAddressW",
    "WSAStartup",
    "WSAUnadvertiseProvider",
    "WSAUnhookBlockingHook",
    "WSAWaitForMultipleEvents",
    "WSCDeinstallProvider",
    "WSCEnableNSProvider",
    "WSCEnumProtocols",
    "WSCGetApplicationCategory",
    "WSCGetProviderInfo",
    "WSCGetProviderPath",
    "WSCInstallNameSpace",
    "WSCInstallNameSpaceEx",
    "WSCInstallProvider",
    "WSCInstallProviderAndChains",
    "WSCSetApplicationCategory",
    "WSCSetProviderInfo",
    "WSCUnInstallNameSpace",
    "WSCWriteNameSpaceOrder",
    "WSCWriteProviderOrder",
] 

parser = argparse.ArgumentParser()
parser.add_argument("-n", "--number", help="Function Number (i.e. ws2_17 = 17)")

args = parser.parse_args()

if(args.number is None):
    parser.print_help(sys.stderr)
    exit()

print("\n WS2_32_" + args.number + " = " + ws2_array[int(args.number)])
